name: Get latest successful release
description: Get latest successful release
author: 'Recharge'

branding:
  icon: 'heart'
  color: 'green'

inputs:
  github-token:
    description: 'Your github token'
    required: true
  github-repo:
    description: 'Your github repository'
    required: true
  github-repo-owner:
    description: 'The github repository owner'
    required: true
  release-workflow-path:
    description: 'The path to the release workflow'
    required: true

outputs:
  latest-successful-release:
    description: The commit sha of the latest successful release
    value: ${{ steps.latest-successful-release.outputs.value }}

runs:
  using: node20
  main: 'dist/index.js'
